# This file helps to configure proxy setting like how we are going to 
# call frontend, backend services, and how the routing will be done

# Simple reverse proxy config for MERN app
# serves frontend at /
# act as proxies to /api/* to backend service

# set headers so that backend can see original host & client IP
# setting the NGINX blocks below

events {

}

http {
    # Limit max upload content to 10 mb
    client_max_body_size 10m;
    # Virtual website that listen to particular port, default is port 80
    server {
        # List to port 80 for all web requests
        listen 80;
        # Create route two location blocks, one for / frontend and another one /api/* for backend
        # when some one visits / or homepage, send this request to frontend service 
        location / {
            # Here, the frontend refers to the container name
            proxy_pass http://frontend:5173;
            # Preserve the original host header
            proxy_set_header Host $host;
            # Provide the client's real IP and not the Nginx's IP to the frontend/backend services via header 
            proxy_set_header X-Real-IP $remote_addr;
            # Forward the original request protocol (either http or https) 
            proxy_set_header X-Forwarded-Proto $scheme;
            # To avoid any buffering 
            proxy_buffering off;
        }

        # when some one hits /api or /api/*, send this request to backend service 
        location /api {
            # Here, the backend refers to the container name
            proxy_pass http://backend:5000;
            # Preserve the original host header
            proxy_set_header Host $host;
            # Provide the client's real IP and not the Nginx's IP to the frontend/backend services via header 
            proxy_set_header X-Real-IP $remote_addr;
            # Forward the original request protocol (either http or https) 
            proxy_set_header X-Forwarded-Proto $scheme;
            # Set the timeout values
            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

        # Optional settings
        location = /nginx-health {
            return 200 "ok";
            add_header Content_Type text/plain;
        }
    }

    # HTTPS configuration
    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/selfsigned.key;

        location / {
            proxy_pass http://frontend:5173;
        }

        location /api/ {
            proxy_pass http://backend:5000;
        }
    }
}