#This is the workflow name/label which will be shown in the github action cy
name: build-and-lint

#Define below triggers when this workflow should run
#Trigger the workflow whenever there is a change to the main and dev branches
# Trigger the workflow whenever there is a pull request for the main and dev branches 

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Backend
      - name: Install backend dependencies
        working-directory: server
        run: npm ci

      - name: Lint backend
        working-directory: server
        run: npm run lint -- --max-warnings=0

      # Frontend
      - name: Install frontend dependencies
        working-directory: client
        run: npm ci

      - name: Lint frontend
        working-directory: client
        run: npm run lint -- --max-warnings=0

      - name: Build frontend
        working-directory: client
        run: npm run build
